export const FETCH_TRAVEL = 'FETCH_TRAVEL'
export const PLACE_ALL = 'ALL'
export const PLACE_ATTRACTION = 'ATTRACTION'
export const PLACE_RESTAURANT = 'RESTAURANT'
export const LOGIN = 'LOGIN'
export const REGISTER = 'REGISTER'
export const DEFAULT_IMAGE = '/defaultImage.jpg'
export const DEFAULT_USER = '/defaultUser.jpg'
export const DEFAULT_LOGO = '/logo.svg'
export const DEFAULT_LOGIN = '/defaultLogin.png'
export const IS_LOGIN = true
export const CATEGORY_BORDER_ALL = "5px solid #00B4E9"
export const CATEGORY_BORDER_ATTRACTION = "5px solid #48cfad"
export const CATEGORY_BORDER_RESTAURANT = "5px solid #f7d25b"
export const ALL_BACKGROUND = "#00B4E9"
export const ATTRACTION_BACKGROUND = "#48cfad"
export const RESTAURANT_BACKGROUND = "#f7d25b"
